// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using miniShop.Infrastructure.Data;

#nullable disable

namespace miniShop.Infrastructure.Migrations
{
    [DbContext(typeof(MiniShopDbContext))]
    [Migration("20230724115338_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("miniShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Müzik"
                        });
                });

            modelBuilder.Entity("miniShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Bermuda",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Şort",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Dell",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Laptop ",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Davul seti",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Davul",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "V Yaka",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Tişört",
                            Price = 250m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Blazor",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Ceket",
                            Price = 250m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Top Crop",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Top Crop",
                            Price = 250m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Insta-tihgt",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/18/47636736/357341652/2/2_org.jpg",
                            Name = "Tayt",
                            Price = 250m
                        });
                });

            modelBuilder.Entity("miniShop.Entities.Product", b =>
                {
                    b.HasOne("miniShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("miniShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
